# config.yaml
# Unified configuration for the autonomous driving system

orchestrator:
  node_router_url: "tcp://*:5559"
  state_pub_url: "tcp://*:5560" 
  command_pull_url: "tcp://*:5561"
  node_timeout: 10.0
  poll_timeout: 10

# ZMQ Communication URLs and Topics
zmq:
  # Camera frame streaming
  camera_frame_url: "tcp://localhost:5555"
  camera_frame_topic: "cam_frame"
  
  # Camera frame streaming (reverse)
  camera_frame_reverse_url: "tcp://localhost:5558"
  camera_frame_reverse_topic: "cam_frame_reverse"
  
  lidar_raw_url: "tcp://localhost:5570"
  lidar_raw_topic: "lidar_scan"  

  obstacle_data_url: "tcp://*:5571"
  obstacle_data_topic: "obstacle"

  obstacle_data_sub: "tcp://localhost:5571"
  obstacle_data_sub_topic: "obstacle"


  # HMI commands
  hmi_cmd_url: "tcp://localhost:5527"
  hmi_cmd_topic: "hmi_cmd"
  hmi_direction_topic: "hmi_direction"
  hmi_max_speed_topic: "hmi_maxspeed"
  
  # Steering commands from lane following
  steering_cmd_url: "ipc:///tmp/teleop_cmd.ipc"
  steering_cmd_topic: "lane_assist_angle"
  
  # Distance data from ArUco
  distance_url: "tcp://localhost:5533"
  distance_topic: "aruco_distance"
  
  # Control commands to LLC
  control_cmd_url: "tcp://localhost:5563"
  control_cmd_topic: "teleop_cmd"
  
  # Sensor data from LLC
  sensor_data_url: "tcp://localhost:5568"
  sensor_data_topic: "sensor_data"
  
  # Lane assist status
  lane_status_url: "ipc:///tmp/lane_assist_status.ipc"
  lane_status_topic: "lane_assist_status"

  frame_publish_url: "tcp://*:5553"
  frame_publish_topic: "frame_data"

# Add this section to your config.yaml
realsense_cameras:
  forward_camera_name: 'Intel RealSense D435'  # The name of your forward-facing camera
  reverse_camera_name: 'Intel RealSense D415'  # The name of your reverse-facing camera
  frame_width: 640
  frame_height: 480
  frame_fps: 30

# Camera Configuration
camera:
  forward:
    camera_source: "realsense"
    device_name: "Intel RealSense D435"
    frame_width: 640
    frame_height: 480
    frame_fps: 30
    video_output_file: 'forward_view.mp4'
    use_display: false
  
  reverse:
    camera_source: "realsense"
    device_name: "Intel RealSense D415"
    # camera_source: "opencv"
    # source: 0  # Use OpenCV for forward camera
    frame_width: 640
    frame_height: 480
    frame_fps: 30
    video_output_file: 'reverse_view.mp4'
    use_display: false

# ArUco Detection Configuration
aruco:
  frame_width: 640
  frame_height: 480
  # Tentukan file kalibrasi terpisah untuk setiap arah
  forward_calibration_file: "calibrationd435.yml"
  reverse_calibration_file: "calibrationd415.yml"
  camera_height_m: 1.5
  known_marker_width_m: 0.145

# Lane Detection Parameters
lane_detection:
  hsv_lower: [0, 0, 230]
  hsv_upper: [200, 20, 255]
  perspective_warp: 0.35
  min_contour_area: 180
  max_contour_area: 800
  pixels_to_meters: 0.00725
  segments: 5

# Stanley Controller Parameters
stanley_controller:
  gain: 0.3
  speed_epsilon: 0.000001
  assumed_speed_for_calc: 0.1
  max_speed: 0.3
  kcte: 0.8
  khe: 0.8

# Vehicle Parameters
vehicle_params:
  rpm_to_mps_factor: 0.0025
  max_speed_rpm: 1000.0
  speed_ramp_rate: 700
  brake_ramp_rate: 120
  max_brake_force: 100
  distance_threshold: 0.2
  enable_video_recording: false
  enable_frame_publishing: true

# HMI Configuration
hmi:
  serial_port: '/dev/ttyUSB0'
  baud_rate: 115200

# LLC Interface Configuration
llc:
  serial_port: '/dev/ttyACM0'
  baudrate: 115200
  steer_multiplier: -3.0
  downsample_rate: 10

# Safety Zone Configuration
safety_zone:
  # Area (m) relative to vehicle center-forward [min_x, max_x] dan [min_y, max_y]
  min_x: -0.8
  max_x: 0.8
  min_y: 0.0
  max_y: 2.5
