# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steering_command.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='steering_command.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16steering_command.proto\"+\n\x0fSteeringCommand\x12\x18\n\x10\x61uto_steer_angle\x18\x01 \x01(\x02\x62\x06proto3'
)




_STEERINGCOMMAND = _descriptor.Descriptor(
  name='SteeringCommand',
  full_name='SteeringCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='auto_steer_angle', full_name='SteeringCommand.auto_steer_angle', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['SteeringCommand'] = _STEERINGCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SteeringCommand = _reflection.GeneratedProtocolMessageType('SteeringCommand', (_message.Message,), {
  'DESCRIPTOR' : _STEERINGCOMMAND,
  '__module__' : 'steering_command_pb2'
  # @@protoc_insertion_point(class_scope:SteeringCommand)
  })
_sym_db.RegisterMessage(SteeringCommand)


# @@protoc_insertion_point(module_scope)
